\documentclass{article}

\begin{document}

<<>>=
library(stats)
library(corrplot)
library(MASS)
data(Boston)

?Boston
@


<<>>=
pairs(Boston)
corrplot(cor(Boston))
lm.medv.lstat <- lm(formula = medv ~ lstat, data=Boston)
summary(lm.medv.lstat)
plot(x= Boston$lstat, y= Boston$medv, xlab = "lower status of the population (percent)",ylab = "median value of owner-occupied homes in $1000s")
abline(lm.medv.lstat)
@

<<>>=

plot(x= Boston$rad, y= Boston$medv)
abline()
@

\end{document}